name: 'medtech_vigilance'
version: '1.0'
config-version: 2

profile: 'medtech_vigilance'

models:
  medtech_vigilance:
    +materialized: view
    stg:
      +schema: PUBLIC_STG
      +materialized: view
    marts:
      +schema: PUBLIC_MARTS
      +materialized: table

seeds:
  medtech_vigilance:
    +schema: PUBLIC_STG
    +quote_columns: false
